// Generates src/tokens.css from the TS tokens so web and native never drift.
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const { light, dark, categoryColors, radius, fontFamily, fontSize, control, motion } =
  await import("../src/index.ts");

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
const vars = (obj, prefix) =>
  Object.entries(obj)
    .map(([k, v]) => `  --${prefix}-${kebab(k)}: ${typeof v === "number" ? `${v}px` : v};`)
    .join("\n");

const css = `/* AUTO-GENERATED by packages/tokens/scripts/build-css.mjs — do not edit. */
:root {
  color-scheme: light;
${vars(light, "c")}
${vars(categoryColors, "cat")}
${vars(radius, "r")}
${vars(fontSize, "fs")}
${vars(control, "ctl")}
  --font-sans: ${fontFamily.sans};
  --font-mono: ${fontFamily.mono};
  --dur-fast: ${motion.duration.fast}ms;
  --dur-base: ${motion.duration.base}ms;
  --dur-slow: ${motion.duration.slow}ms;
  --ease-standard: ${motion.easing.standard};
  --press-scale: ${motion.pressScale};
}
:root[data-theme="dark"] {
  color-scheme: dark;
${vars(dark, "c")}
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${vars(dark, "c").replace(/^/gm, "  ")}
  }
}
`;
writeFileSync(resolve(here, "../src/tokens.css"), css);
console.log("tokens.css written");
